### ISSUE TITLE
States not working properly when publishing answer

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-questions#13]
**Describe the bug**
When publishing answer the state doesn't change to "Retenue", the answer is not published and the state remains en "attente de validation".

**To Reproduce**
1. Accept an answer.
2. Check the question page, the answer is not published nor the anwser.

**Expected behavior**
The state should change to "Réponse publiée" (translation needs to be changes it's retenue right now and the answer should be published.

**Screenshots**

**Stacktrace**
If applicable, add the error stacktrace to help explain your problem.

**Extra data (please complete the following information):**
- Decidim module : https://test.cndp.opensourcepolitics.eu/processes/occaecati-est/f/10/questions/5
- Decidim installation: test.cndp.opensourcepolitics.eu

**Comment by lu-hamani** [comment]
@armandfardeau @moustachu 
The exact bug is that the state of the answer doesn't change to "Retenue", as it should, when the admin change the state from the answer view.
When as an admin I do it from the "Modifier la question" view, the change is effective

**Comment by armandfardeau** [comment]
@lu-hamani Must be a permission issue, i will check asap

**Comment by lu-hamani** [comment]
> @lu-hamani Must be a permission issue, i will check asap

👍

**Comment by armandfardeau** [comment]
@lu-hamani I've checked and have not been able to reproduce, maybe instance was not up to date?
