### ISSUE TITLE
We should hide questions that are "non retenues"

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-questions#21]
I've done a little css wonder to hide these filters  https://participons.debatpublic.fr/processes/nfl/f/37/
- "Toutes les questions"
- "Non retenues"

We should hide the once labelled "non retenue" and not display these filtering options. Happy to discuss this @lu-hamani maybe we stick with the little css trick.

**Comment by lu-hamani** [comment]
@virgile-dev 
Let's talk about this one. First can you tell me what is your trick ? thanks

**Comment by lu-hamani** [comment]
@virgile-dev 
This one we have done through css trick. I suggest we reopen it the solution isn't lasting.
