### ISSUE TITLE
Cannot translate some keys with the translation module

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-questions#22]
Here is a list from my exlorations :

Cards being called outside of the question index don't take on translations. 
A few examples :

- Presentation page of a participatory process
<img width="765" alt="Capture d’écran 2019-04-16 à 21 30 07" src="https://user-images.githubusercontent.com/11473995/56238858-c8fb1a00-608f-11e9-864c-e40d56668e95.png">

- Following tab of the public profile
<img width="755" alt="Capture d’écran 2019-04-16 à 21 37 07" src="https://user-images.githubusercontent.com/11473995/56238905-e92ad900-608f-11e9-8f15-1d248ad4e7cd.png">
_This is a "Avis"_

**Comment by moustachu** [comment]
@armandfardeau First things to test is to check if the `decidim-term_customizer` module works outside of the scope of the translation set constraints. 
There's a good chance that it's an issue with the Controllers only loading translation for these constraints

**Comment by lu-hamani** [comment]
To report to main repo and reframe as an enhancement for module term customizer.
