### ISSUE TITLE
Feature request list from CNPD

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-questions#25]
1. Ability to move questions between tabs (avis, question réponse, contribution)
2. Numérotation des questions
3. Assigner une question à un utilisateur précis

**Comment by lu-hamani** [comment]
@virgile-dev 
More detailed issues were written for each request : 
- #27 = Question numerotation
- #26 = participations transfers among components
- #16 = question assignment

Do not hesitate to comment there !
