### ISSUE TITLE
Question transfer

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim-questions#26]
**Is your feature request related to a problem? Please describe.**
Users often mistakenly publish questions in "avis" or "contributions" components or the other way around as well. This is making things difficult for an admin to process a user's participation and impede the workflow.

**Describe the solution you'd like**
As an admin I want to transfer users participations from a component to another so that participations are located in the right component and I am able to process them appropriately. 

**Acceptance criteria**
When transferred, a participation should only appear in the component it has been transferred to.

**Alternatives considered**
We've considered using the existing "important from other functionnality" but it doesn't work as they are not transfered but just copied from a component to another also admins need to this per question, currently it is done by status.

**Comment by virgile-dev** [comment]
Here is a mockup of how this would render : 
![Capture d’écran 2019-04-25 à 15 19 05](https://user-images.githubusercontent.com/11473995/56738824-b78bcf00-676d-11e9-92b3-e39fe893e52d.png)

![Capture d’écran 2019-04-25 à 15 20 41](https://user-images.githubusercontent.com/11473995/56738819-b65aa200-676d-11e9-8fb2-9f600400d417.png)

**Comment by moustachu** [comment]
rewrited in #30
