### ISSUE TITLE
Question numbering

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim-questions#27]
**Is your feature request related to a problem? Please describe.**
Both admins and users fall back on questions id to reference it in a new question, "avis", contribution or answer to any of those 3.
Participations id are not highlighted enough in the current layout since it appears only in the participation url or within the much longer participation reference on the bottom right corner of the participation view.

**Describe the solution you'd like**
Participation id should be displayed next to the participation title.

**Describe alternatives you've considered**
It could be displayed in other locations in the participation view as long as it is immediately seen by the user or admin when accessing the page.

**Comment by virgile-dev** [comment]
Maybe the best way to handle this is to propose them to make the numbering themselve.
