### ISSUE TITLE
CPDP (comittee) are receiving many notification emails they should not receive

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-questions#29]
Acording to Sofia CPDP should only receive these 2 notifications : 
- Quand une question leur est affectée (à traiter / CPDP)
- Quand le MO répond à une question et que la réponse doit être validée.

From her last email it looks like they are receiving many more.
Is there a quick fix like unfollowing the process ?

**Comment by lu-hamani** [comment]
@virgile-dev 

> From her last email it looks like they are receiving many more.
> 

They are since they have the same permissions as an admin.

> Is there a quick fix like unfollowing the process ?
> 
Could be. I have to check.
What could be heplful, is that they give us a table listing all the notifications they want for each role. We could then deal with it once and for all.

**Comment by virgile-dev** [comment]
OK @lu-hamani I'm gonna ask for it.
