### ISSUE TITLE
Select individual recipients in Questions workflow

### ISSUE THREAD

**Issue by moustachu** [OpenSourcePolitics/decidim-questions#31]
## Is your feature request related to a problem? Please describe.
Administrators ask for the selection of individual recipients instead of a role (_committee_ or _service_) when updating the Question state (_evaluating_).

_see **Additional context** for more details on the module workflow_

## Describe the solution you'd like
When moving the Question in the workflow (updating state / recipient), user can select multiple users as recipient (instead of all the users with the targeted role) : 
- [x] Add a **new attribute `recipient_ids`** on the `Question` model to store multiple user ID.
- [x] Update the recipient sub-form on the **Question admin edit form** with a `select` control of the targeted role users (_see screenshots in **Additional context**_)
- [x] Restrict the **Question admin index** list with the selected recipient (_see details in **Additional context**_)
- [x] Update Notifications recipients according to the selected recipients.

➡️ ⚠️ **These enhancements should be made from the [`feature/upstream_moderation`](https://github.com/OpenSourcePolitics/decidim-questions/tree/feature/upstream_moderation) branch**

> Note : `Permissions` will be handle in another issue.

## Describe alternatives you've considered
"Component roles" and a more advanced workflow management system were discussed but the complexity and impact on the whole platform did not fit the planning related to this enhancement. 

## Additional context & Details
> Reminder : Questions is a clone (0.16) of the Proposals module with additional roles and a custom moderation workflow. 

On the Question workflow, the `committee` and `service` roles are used to distribute Questions to corresponding user groups when the Question is being evaluated / answered. This impact Question visibility, actions and notifications for this users. 

### New attribute `recipient_ids`
> We keep the existing `recipient` attribute on the `Question` model to indicate which role are targeted.  

Add a **new attribute `recipient_ids`** on the `Question` model to store multiple user IDs. 

### Question admin index
On the component admin index, `service` users are **only** able to see the Questions whom they are **recipient** for. 
> No change for Admins and `committee` users : they are able to see everything.

### Question admin edit form
Prior to this enhancement, the Question admin edit form was updated to be able to : 
- Select the state of the Question
- When the state was "evaluating", select the recipient of the Questions (`none`/`committee`/`service`)
- When the state was "accepted" or "rejected", directly answer the Question from this form

This enhancement add a new step :  
When the recipient is a role (`committee`/`service`), display a component to select users (filtered by the targeted role). The `select` component must be set with options : 
- multiple selection enabled
- first and default option to `<all>` (which will select all users in the list)

<img width="751" alt="Capture d’écran 2019-05-09 à 15 36 17" src="https://user-images.githubusercontent.com/464350/57458142-1f174380-7271-11e9-8fcb-74e2155423b3.png">

<img width="751" alt="Capture d’écran 2019-05-09 à 15 40 48" src="https://user-images.githubusercontent.com/464350/57458160-26d6e800-7271-11e9-9552-8058744cac50.png">

## Update Notifications recipients
Notifications recipients defined in the `Decidim::Questions::Admin::UpdateQuestion` (`app/commands/decidim/questions/admin/update_question.rb`) command must be updated to restrict them only to selected users.

**Comment by oriolgual** [comment]
@moustachu I can't find any code related to notifications at `app/commands/decidim/questions/admin/update_question.rb`, is this at `master` or another branch?

**Comment by oriolgual** [comment]
What about existing questions, should we migrate them to add all the committee / service users for that participatory space?

**Comment by oriolgual** [comment]
> No change for Admins and committee users : they are able to see everything.

If commitee users are able to see everything why add the possibility to select which users? What effect has selecting a specific commitee user?

**Comment by moustachu** [comment]
@oriolgual My Bad ! I was so focused on task scheduling and client validation that I did forgot to mention the branch part ... 

The most advanced branch is https://github.com/OpenSourcePolitics/decidim-questions/tree/feature/upstream_moderation and should be the starting point for your developments.

**Comment by oriolgual** [comment]
@moustachu could you please review the other questions?

**Comment by moustachu** [comment]
@oriolgual 

Migrations : Indeed ! We should add a migration to add **all** the user with the targeted role to the `recipients` new attribute

Committee visibility : In this case, this will only affect notifications to the selected committee users. We wanted to also filter the visibility but the client didn't validate this point ...

**Comment by oriolgual** [comment]
@moustachu it seems that branch is missing the `UpstreamModerationsController`. I'm also getting errors with `UpstreamReportable` and `upstream_not_hidden`

**Comment by moustachu** [comment]
@oriolgual `UpstreamModerationsController` is here on the core Decidim gem : 
https://github.com/OpenSourcePolitics/decidim/blob/0.16-upstream_moderation/decidim-admin/app/controllers/decidim/admin/upstream_moderations_controller.rb

(with a specific branch [`0.16-upstream_moderation`](https://github.com/OpenSourcePolitics/decidim/tree/0.16-upstream_moderation)
