### ISSUE TITLE
Display publishing date

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-questions#38]
**Is your feature request related to a problem? Please describe.**
As question works with different visibility setting depending on the state and service have to answer questions on a certain deadline it is important to display the form submission date and the publishing date.

The publishing date = the moment the question changes state for `evaluating` or `accepted`.

**Describe the solution you'd like**
Show publishing date on the relevant screens, here is the checklist for the corresponding screens to design:

- [x] The publishing date = the moment the question changes state for `evaluating` or `accepted`.
- [x] Screen for question view
- [x] Screen for admin /manage
- [x] Screen for admin /edit
- [x] Screen for admin /question_notes
- [x] Screen for admin /question_answers
- [x] In the admin the counter `date-ago` displaying date with "Il y a X min/heure/mois" will have to be updated based on the publishing date.

**Comment by virgile-dev** [comment]
question view
![date show](https://user-images.githubusercontent.com/11473995/57796263-3e6a1100-7748-11e9-8197-2cfdd3bc387b.png)

**Comment by virgile-dev** [comment]
/edit, /question_answers, /question_notes
![note](https://user-images.githubusercontent.com/11473995/57796319-5f326680-7748-11e9-84ff-923b6abef88a.png)

**Comment by virgile-dev** [comment]
/manage
![mange$](https://user-images.githubusercontent.com/11473995/57796648-eed81500-7748-11e9-9919-497f83f49d23.png)

**Comment by virgile-dev** [comment]
[Recette]@moustachu
- [x] Submission date appears twice we should delete the original one
![Capture d’écran 2019-05-21 à 11 18 34](https://user-images.githubusercontent.com/11473995/58084287-e05f8280-7bba-11e9-95a7-b54e1d87e805.png)
- [x] Publishing date changes when going from `evaluating` to `accepted`, we should keep the date when the proposal changed from `a traiter` to `evaluating
- [x] in the /manage view a question that is `a traiter` can't display a value for the column "Publiée" because it's not published yet, same goes for the questions that have the state `rejected`.
![Capture d’écran 2019-05-21 à 11 27 57](https://user-images.githubusercontent.com/11473995/58084758-c3777f00-7bbb-11e9-90fb-54977441637b.png)

I've been doing my testing on : https://test.cndp.opensourcepolitics.eu/admin/participatory_processes/DebatNFL/components/74/manage/questions

**Comment by moustachu** [comment]
#### Changes made (4ff289c74) :
- Remove the duplicate Publication date on the Questions `show` view 
- Publication date **is only updated** when state **changes** to `accepted`
- **In all views** (front & admin) : the publication date is only displayed when the state is `accepted`

**Comment by virgile-dev** [comment]
Hey @moustachu,

Published question = visible to all users
A published question can correspond to 3 states
- `accepted`
- `evaluating`
- and calculated stats `en attente de validation`

In these terms, publish date = first date recorded when a question changes to one of these 3 states.
Is it feasable technically ?

**Comment by virgile-dev** [comment]
Hi @moustachu 
Did you ended up solving this ?
I have tickets from [JY](https://support.opensourcepolitics.eu/scp/tickets.php?id=202) showing versionning logs that show that the publication date is not right.

For example, [this one](https://participons.debatpublic.fr/processes/nfl/f/38/questions/303/versions) says it's been published 01/05/2019 21:57
But the logs show that the change of state was on 06/05/2019 11:40

**Comment by virgile-dev** [comment]
@armandfardeau why did you close this? Has it been fixed already? 
If you have any questions regarding the publishing date please come to me. In fact, let's take 5 min and talk about this issue.

**Comment by armandfardeau** [comment]
@virgile-dev Ping me when you have five minutes.
