### ISSUE TITLE
Wrong role on Participartory Process User update

### ISSUE THREAD

**Issue by moustachu** [OpenSourcePolitics/decidim-questions#4]
**Describe the bug**
When updating a Process User inside a Participatory Process, the user role is **not** properly selected when loading the form, the select input is positioned on the default value (same as a new form). 

**To Reproduce**
1. Go to 'Admin dashboard'
2. Go to 'Process list'
3. Go to 'Open a participatory process'
3. Go to 'Process user list'
2. Click on a user after noticing his role (other than 'admin', as it is the default selected)
4. See the wrong selected role (default value --> 'admin')

**Expected behavior**
When updating a Process User inside a Participatory Process, the user role is **properly** selected when loading the form. 

**Screenshots**

<img width="1365" alt="capture d ecran 2019-01-13 a 18 51 43" src="https://user-images.githubusercontent.com/464350/51088809-bd344a80-1764-11e9-80b4-42e40c90eeff.png">

<img width="1107" alt="capture d ecran 2019-01-13 a 18 54 11" src="https://user-images.githubusercontent.com/464350/51088812-c9b8a300-1764-11e9-8e96-26cbfa9a0e13.png">

**Additional context**
This issue is not due to custom code and is present on the origin repository [decidim/decidim](https://github.com/decidim/decidim). 
**This need to be fixed there first and then merged on this repository.**

**Comment by virgile-dev** [comment]
@armandfardeau just checked this on the production instance participons.debatpublic.fr the bug is still there.
