### ISSUE TITLE
Bug with question creation date

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-questions#60]
**Describe the bug**
We have an issue with the creation date for this [Question.](participons.debatpublic.fr/processes/nfl/f/37/questions/615/)

It displays 05/06/2019 14:22 when all the versionning dates from the 12/06.
<img width="1118" alt="Capture d’écran 2019-06-19 à 16 24 00" src="https://user-images.githubusercontent.com/11473995/59774002-f1c9a680-92ae-11e9-9d45-07b464f54e01.png">

If we can have a diagnostic for this bug it would be great.

**Comment by moustachu** [comment]
@virgile-dev I can confirm you that this question was created on the 05/06/2019 : 
- the `created_at` date is set to 05/06/2019
- the corresponding action log are also set on 05/06/2019 for the action `create`

**Comment by virgile-dev** [comment]
So weird, It's hard for me to go back to the client with that answer.
The question supposedly emerged from a meeting that was hold on the [11/06 ](https://noeud-ferroviaire-lyonnais.debatpublic.fr/reunion-venissieux-1106) so it's hard to think it was created on 05/06. 
Maybe we should just correct the date in db ? What do you think ?
