### ISSUE TITLE
Can't access the process (process admin) - Decidim-Questions

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim-questions#7]
**Describe the bug**
I am process admin and I can't access the process BO 

**To Reproduce**
1. Go to 'Admin panel'
2. Click on 'Concertations'
3. See error

**Expected behavior**
i should be able to access the process BO

**Screenshots**
<img width="1440" alt="screenshot 2019-02-18 at 14 47 15" src="https://user-images.githubusercontent.com/32680605/52958131-ba47fd80-3393-11e9-8394-c776f372e063.png">

**Comment by armandfardeau** [comment]
@lu-hamani Would you mind adding a link to this issue?

**Comment by armandfardeau** [comment]
@moustachu The server must be reloaded. This is linked to the extends.

**Comment by armandfardeau** [comment]
@moustachu Can we close this issue?
