### ISSUE TITLE
Answer to questions shouldn't be multilingual

### ISSUE THREAD

**Issue by lu-hamani** [OpenSourcePolitics/decidim-questions#8]
**Describe the bug**
As a service, you can provide different answers according to the platform language. While it is an interesting behaviour, it doesn't match the behaviour to create questions (as a user or official)

**To Reproduce**
1. Create a question as a user in french
2. Assign it to "service" in the BO
3. As a service, provide an answer in english
4. See error in BO as an admin

**Expected behavior**
As the question creation is unilingual, answers provided should unilingual as well.

**Comment by armandfardeau** [comment]
@lu-hamani Is @virgile-dev okay with this?

**Comment by armandfardeau** [comment]
@moustachu I've talked with @lu-hamani about this. This feature is useful when the city needs to answer in multiple languages as a legal obligation (Switzerland, Belgium etc...) 

To avoid this behavior I suggest that we disable multiple locales instead of altering this feature.
